vim.api.nvim_set_keymap('i', 'jk', '<ESC>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'jK', '<ESC>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('i', 'JK', '<ESC>', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'H', '^', { noremap = true })
vim.api.nvim_set_keymap('n', 'L', '$', { noremap = true })
vim.api.nvim_set_keymap('v', 'H', '^', { noremap = true })
vim.api.nvim_set_keymap('v', 'L', '$', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>o', 'o<Esc>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>O', 'O<Esc>', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>C', 'v^c', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>S', 'v^s', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>D', 'v^d', { noremap = true })
vim.api.nvim_set_keymap('n', '<Leader>V', 'v^', { noremap = true })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>")
vim.api.nvim_set_keymap('n', 'J', '10jzz', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'K', '10kzz', { noremap = true, silent = true })
vim.api.nvim_set_keymap('v', 'J', '10jzz', { noremap = true, silent = true})
vim.api.nvim_set_keymap('v', 'K', '10kzz', { noremap = true, silent = true})
vim.api.nvim_set_keymap('n', 'j', 'gj', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', 'k', 'gk', { noremap = true, silent = true })
vim.api.nvim_set_keymap('n', '<c-x>', '<c-v>', { noremap = true })
vim.api.nvim_set_keymap('', '<Esc><Esc>', ':nohlsearch<CR><ESC>', { noremap = true })
vim.keymap.set('n', 'ge', '<cmd>lua vim.diagnostic.open_float()<CR>')
vim.keymap.set('n', 'g]', '<cmd>lua vim.diagnostic.goto_next()<CR>')
vim.keymap.set('n', 'g[', '<cmd>lua vim.diagnostic.goto_prev()<CR>')
